[programs.localnet]
todo = "DbwyCYv83xm4TvTNtUFp8LwtKFtwaKK4P1HcDjAktoLb"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/dimfeld/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
